### DISCUSSION TITLE
Type error when using `!important` when `strictTokens: true`

### DISCUSSION THREAD

**Discussion by bengry** [chakra-ui/panda#1003] [General]
### Description

When `strictTokens` is `true`, TypeScript errors on this (both lines) [playground link](https://play.panda-css.com/lFXzleFNXf):
```tsx
 <div
      className={css({
        width: '20!',
        bg: 'red.100 !important',
      })}
    />
```

The generated CSS is correct though:
```css
@layer utilities {
  .w_20\! {
    width: var(--sizes-20) !important
    }

  .bg_red\.100\! {
    background: var(--colors-red-100) !important
    }
}
```

So this is probably just a type issue.

### Link to Reproduction

https://play.panda-css.com/lFXzleFNXf

### Steps to reproduce

1. Go to https://play.panda-css.com/lFXzleFNXf
2. See errors

### Panda CSS Version

0.6.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
