### DISCUSSION TITLE
expand `colorPalette` flexibility

### DISCUSSION THREAD

**Discussion by VinSpee** [chakra-ui/panda#1103] [Ideas]
### Description

expand the flexibility of the Virtual Color feature by allowing for un-opinionated nested object definitions

### Problem Statement/Justification

Hi! I've been using panda in two large projects. As a former Chakra user and a tailwind tolerator, I was delighted to hop on the panda train as quickly as possible and guide my teams in that direction.

One idea I really like is [Virtual Color](https://panda-css.com/docs/guides/virtual-color).

I like to build component libraries in a very flexible way, and a technique I use is to provide `aesthetic` and `color` props. In panda, I model it like this:

```ts
const config = defineConfig({
	theme: {
		tokens: {
			blue: {
				50: {
					value: 'blue'
				},
				900: {
					value: 'cyan'
				}
			},
			red: {
				50: {
					value: 'red'
				},
				900: {
					value: 'magenta'
				}
			}
		}
	}
});

const buttonRecipe = defineRecipe({
	name: 'button',
	base: {
		…baseProps
	},
	variants: {
		color: {
			blue: {
				colorPalette: 'blue',
			},
			red: {
				colorPalette: 'red',
			}
		},
		aesthetic: {
			solid: {
				backgroundColor: 'colorPalette.50'
				color: 'colorPalette.900'
			}
		}
	}
});
```

This is straightforward enough.

However, in my current project, we're taking an approach where we lean into semantic tokens, with a theme configuration like so:

```ts
const config = defineConfig({
	theme: {
		semanticTokens: {
			core: {
				light: {
					DEFAULT: {
						value: 'blue'
					},
					accent: {
						value: 'cyan'
					}
			},
			brand: {
				light: {
					DEFAULT: {
						value: 'red',
					},
					accent: {
						value: 'magenta'
					}
				}
			}
		}
	}
})
```

which means I want to define my button like this:

```ts
const buttonRecipe = defineRecipe({
	name: 'button',
	base: {
		…baseProps
	},
	variants: {
		color: {
			core: {
				colorPalette: 'core',
			},
			brand: {
				colorPalette: 'brand',
			}
		},
		aesthetic: {
			solid: {
				backgroundColor: 'colorPalette.light'
				color: 'colorPalette.light.accent'
			}
		}
	}
});
```

This doesn't work.

### Proposed Solution or API

I see [in the docs that `colorPalette` requires 50–900 keys](https://panda-css.com/docs/guides/virtual-color#:~:text=%F0%9F%92%A1-,Important%3A%20A%20valid%20colorPalette%20value%20is%20an%20color%20object%20that%20has%2050%20to%20900%20keys.,-const%20className%20%3D).

1. Why does `colorPalette` have an opinion about its shape?
2. Would it be reasonable to expand the flexibility of Virtual Colors to allow for nested tokens?

### Alternatives

- altering my color palette to use `50`-`900`
- not using `colorPalette` or Virtual Color at all

### Additional Information

Here's a failing case: https://play.panda-css.com/XIIQGvJhd9

Thanks for the excellent work on the project – it makes building UIs so fun, and is the most lovely successor to chakra, which I loved for a long time.

**Comment by isBatak** [comment]
@VinSpee 
It seems like it mostly works, only the hover state is not detected 🤔
https://play.panda-css.com/ebvVxk8H8U

**Comment by VinSpee** [comment]
> @VinSpee 
> 
> It seems like it mostly works, only the hover state is not detected 🤔
> 
> https://play.panda-css.com/ebvVxk8H8U

Exactly. The nested case fails (has nothing to do with the hover state, it's due to that token being nested an additional level)

**Comment by p7gg** [comment]
Yeah, the ability to extend this functionality would be huge...
For instance I want to use it with @radix-ui/colors but I can't, cuz its color objects have 12 keys

**Reply by isBatak** [reply]
@p7gg could you share a playground reproduction of this issue?

Link to playground https://play.panda-css.com/

**Reply by isBatak** [reply]
@p7gg you can already do this, check it here https://play.panda-css.com/lCHlTlE7yu

**Reply by trangcongthanh** [reply]
@p7gg I wrote a small function to transform @radix-ui/colors into semanticTokens.

```typescript
import * as colors from '@radix-ui/colors'

type SemanticToken = {
	value: {
		base: string
		_dark?: string
		_osDark?: string
	}
	description?: string
}

function transformColorsToTokens() {
	const transformed = Object.entries(colors).reduce((a, [colorName, values]) => {
		const isDark = colorName.includes('Dark')

		Object.entries(values).forEach(([scale, value]) => {
			const token = a.get(scale) ?? ({ value: {} } as SemanticToken)
			token.description = scale
			if (isDark) {
				token.value['_dark'] = value
				token.value['_osDark'] = value
			}
			if (!isDark) {
				token.value['base'] = value
			}
			a.set(scale, token)
		})

		return a
	}, new Map<string, SemanticToken>())
	return Object.fromEntries(transformed.entries())
}
export default defineConfig({
	theme: {
            extend: { semanticToken: { colors: transformColorsToTokens() } }
	},
})
```
Usage:
```jsx
<div className={css({ color: 'blue12', backgroundColor: 'slate1' }} />
```

**Comment by isBatak** [comment]
@VinSpee could you please check it in this Draft build of playground https://panda-playground-git-issue-1062-expand-colorpa-125510-chakra-ui.vercel.app/? 
It's based on this Draft PR https://github.com/chakra-ui/panda/pull/1166 and I think it should cover all of the cases 🤞 :D

**Reply by VinSpee** [reply]
@isBatak looks like this adds the custom property correctly, but still doesn't interpolate correctly, here's the output of my test cast:

```css
@layer utilities {
  .color-palette_core {
    --colors-color-palette-dark: var(--colors-core-dark);
    --colors-color-palette-light: var(--colors-core-light);
    --colors-color-palette-light-accent: var(--colors-core-light-accent);
  }

  .text_light {
    color: light;
  }

  .bg_dark {
    background-color: dark;
  }

  .hover\:text_light\.accent:is(:hover, [data-hover]) {
    /* this isn't right */
    color: light.accent;
  }
}

```

**Reply by isBatak** [reply]
@VinSpee could you share the whole example?

To me it seems like it works:
```css
@layer utilities {
  .color-palette_core {
    --colors-color-palette-light: var(--colors-core-light);
    --colors-color-palette-light-accent: var(--colors-core-light-accent);
  }

  .text_colorPalette\.light {
    color: var(--colors-color-palette-light);
  }

  .hover\:text_colorPalette\.light\.accent:is(:hover, [data-hover]) {
    color: var(--colors-color-palette-light-accent);
  }
}
```
config
```js
import { defineConfig } from '@pandacss/dev';

export const config = defineConfig({
  theme: {
		semanticTokens: {
      colors:{
        core: {
          light: {
            DEFAULT: {
              value: 'blue'
            },
            accent: {
              value: 'cyan'
            }
          }
        },
        brand: {
          light: {
            DEFAULT: {
              value: 'red',
            },
            accent: {
              value: 'magenta'
            }
          }
        }
      }
    }
	}
});    
```
code:
```tsx
import { css } from 'styled-system/css'

export const App = () => {
  return (
    <>
      <button
        className={css({
          colorPalette: 'core',
          color: 'colorPalette.light',
          _hover: {
            color: 'colorPalette.light.accent'
          }
        })}
      >
        Hello world
      </button>
    </>
  )
}
```
