### DISCUSSION TITLE
Combine selector and media query in condition?

### DISCUSSION THREAD

**Discussion by Pinpickle** [chakra-ui/panda#1216] [Q&A]
I want a hover selector that doesn't apply on mobile devices

I want to write:

```ts
css({
  _hover: {
    color: "green",
  }
})
```

And it expand to something like
```css
@media (pointer: fine) {
  &:hover {
     color: green;
  }
}
```

I know conditions can be written as a selector or a media query. Is there a way to combine both?
