### DISCUSSION TITLE
Switching atomic css to classless in config

### DISCUSSION THREAD

**Discussion by kogeletey** [chakra-ui/panda#1218] [Ideas]
Sometimes, it is necessary to use one css file with a minimum number of classes.
For example, such an opportunity is needed when creating a blog.
Witch static generation of articles, the amount of code with classes significantly exceeds the amount of html code without classes.

**Comment by anubra266** [comment]
@kogeletey please explain more about what you mean

**Comment by kogeletey** [comment]
For example, writing the following code on panda
```tsx
const styles = css({
  backgroundColor: 'gainsboro',
  borderRadius: '9999px',
  fontSize: '13px',
  padding: '10px 15px'
})
 
<div className={styles} atomic="false" />
```

 would generate css

 ```css
 div:where(hash) {
   background-color: gainsboro;
   border-radius: 9999px;
   font-size: 13px;
   padding: 10px 15px;
 }
 ```
 
 or some other way to specify this setting
