### DISCUSSION TITLE
Referencing reciple className in selector

### DISCUSSION THREAD

**Discussion by FlatMapIO** [chakra-ui/panda#1247] [Q&A]
I saw code like this in radix-theme:

```css
.rt-Link {
  &:where(.rt-underline-auto) {
    &.rt-high-contrast, 
    :where(.rt-Text:where([data-accent-color])):not(.rt-high-contrast) & {
      text-decoration-line: underline;
      text-decoration-color: var(--accent-a6);
    }
  }
}
```

If I were to implement this in pandacss, where Link and Text are two different Recipes, is there a reliable way to reference the Text or Text.slotA classname in the selector?
