### DISCUSSION TITLE
mono font family variable fallback in css preflight

### DISCUSSION THREAD

**Discussion by smarlhens** [chakra-ui/panda#1704] [Q&A] [answered]
Hi there 👋🏻 ,

Thanks for your amazing job on this library.

I have a question (maybe dumb) regarding font fallback value on mono family in preflight css reset: I see that `--font-fallback` is used as backup for `--global-font-mono`. Is it expected or should it be `--font-mono-fallback` defined just above ?

```scss
${selector}pre {
  font-size: 1em;
  --font-mono-fallback: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New';
  font-family: var(--global-font-mono, var(--font-fallback)); // <----- HERE
}
```
[source](https://github.com/chakra-ui/panda/blob/69140cde143cbba577f5ff3fbf1c6b6181c69aca/packages/generator/src/artifacts/css/reset-css.ts#L175C1-L179C4 )

Thanks in advance for your help on this.

I wish you a great day ☀️

Best regards,
Samuel
