### DISCUSSION TITLE
Implementing removal of spinners in numeric inputs.

### DISCUSSION THREAD

**Discussion by MeanBoyCousin** [chakra-ui/panda#2086] [Q&A] [answered]
Been tinkering for a while but for the life of me I can't suss out the syntax here. Any help appreciated.

```css
/* Chrome, Safari, Edge, Opera */
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

/* Firefox */
input[type=number] {
  -moz-appearance: textfield;
}
```

Ref: https://www.w3schools.com/howto/howto_css_hide_arrow_number.asp
