### DISCUSSION TITLE
The backdrop_auto token generated by lightningcss is invalid.

### DISCUSSION THREAD

**Discussion by FlatMapIO** [chakra-ui/panda#2329] [General]
```tsx
css({
backdropFilter: 'auto',
backdropBlur: 'md',
})
```

with lightningcss:
```css
  .backdrop_auto {
    -webkit-backdrop-filter: var(--backdrop-blur) var(--backdrop-brightness) var(--backdrop-contrast) var(--backdrop-grayscale) var(--backdrop-hue-rotate) var(--backdrop-invert) var(--backdrop-saturate) var(--backdrop-sepia);
  }

```

with postcss

```css
  .backdrop_auto {
    backdrop-filter: var(--backdrop-blur) var(--backdrop-brightness) var(--backdrop-contrast) var(--backdrop-grayscale) var(--backdrop-hue-rotate) var(--backdrop-invert) var(--backdrop-saturate) var(--backdrop-sepia);
    -webkit-backdrop-filter: var(--backdrop-blur) var(--backdrop-brightness) var(--backdrop-contrast) var(--backdrop-grayscale) var(--backdrop-hue-rotate) var(--backdrop-invert) var(--backdrop-saturate) var(--backdrop-sepia);
}

```

The -webkit-backdrop-filter has been marked as deprecated, so it's not valid on the page.
