### DISCUSSION TITLE
How do I set webkit fallback value?

### DISCUSSION THREAD

**Discussion by punkpeye** [chakra-ui/panda#2992] [General]
```css
.grabbable {
    cursor: move; /* fallback if grab cursor is unsupported */
    cursor: grab;
    cursor: -moz-grab;
    cursor: -webkit-grab;
}

.grabbable:active {
    cursor: grabbing;
    cursor: -moz-grabbing;
    cursor: -webkit-grabbing;
}
```

What would be the equivalent of this in panda?

I would expect something like this to work:

```css
cursor: ['-webkit-grab', '-moz-grab', 'grab', 'move'],
```

but it does not.
