### DISCUSSION TITLE
Generate class and css without escaping characters

### DISCUSSION THREAD

**Discussion by cnx-ednilsonalbuquerque** [chakra-ui/panda#3087] [General]
Is it possible to change the way classes are generated? For example:

From
```css
class="cnx-c_brand.primary.300"
```

To
```css
class="cnx-c_brand-primary-300"
```

The reason I'm asking is that the escapes in the generated CSS interfere when applying styles using jest-dom, as the CSS ends up like this:

```css
.cnx-c_brand\.primary\.300:not(#\#):not(#\#):not(#\#):not(#\#):not(#\#) {
  color: var(--cnx-colors-brand-primary-300);
}
```

This makes it difficult to work with styles in testing environments.
