### DISCUSSION TITLE
Generate CSS file with all variants

### DISCUSSION THREAD

**Discussion by TheOrdinaryDev** [chakra-ui/panda#854] [Q&A] [answered]
Is it possible to generate CSS file with all variants including the unused ones?
In my use case, the value comes from the runtime and I need to generate all possible variants at build time.

**Comment by astahmer** [comment, marked as answer]
hey, yes you can "static" CSS (as in, always generating it even if no usage found in your app) using [`config.staticCss`](https://panda-css.com/docs/guides/static)

**Comment by TheOrdinaryDev** [comment]
Hello, thanks for your reply. Unfortunately, I cannot configure this so that variants are generated.
My config file
```tsx
// panda.config.ts
import { defineConfig } from '@pandacss/dev';

export default defineConfig({
    include: ['./src/*.{tsx,jsx}'],
    jsxFramework: 'react',
    staticCss: {
        recipes: {
            button: ['*'],
        },
    },
    theme: {
        extend: {
            recipes: {
                button: {
                    name: 'button',
                    base: {},
                    variants: {
                        size: {
                            small: { padding: '6px 12px', height: '32px' },
                            medium: { padding: '8px 16px', height: '40px' },
                            large: { padding: '12px 24px', height: '48px' },
                        },
                    },
                },
            },
        },
    },
});
```
My Button component
```jsx
// src/Button.tsx
import { button } from '../styled-system/recipes';

type ButtonProps = { size: 'small' | 'medium' | 'large' };

export const Button = ({ size = 'medium' }: ButtonProps) => {
    return <button className={button({ size })}>Button</button>;
};
```
When I run `panda` style.css is
```css
@layer reset, base, tokens, recipes, utilities;

@import './global.css';

@import './static.css';

@import './tokens/index.css';

@import './tokens/keyframes.css';

```
When I add a component that uses the variant
```jsx
// src/SmallButton.tsx
import { Button } from './Button';

export const SmallButton = () => {
    return <Button size="small" />;
};
```
and run `panda` style.css is

```css
@layer reset, base, tokens, recipes, utilities;

@import './global.css';

@import './static.css';

@import './tokens/index.css';

@import './tokens/keyframes.css';

@layer recipes {
  .button--size_small {
    padding: 6px 12px;
    height: 32px
    }
}
```
I need to generate style.css with all recipe variant classes and styles without using variant values explicitly in the code.
