### ISSUE TITLE
[v0.7.0] Multiple recipes with variants on the same JSX element bug - only the 1st recipe (as specified in the config) has its chosen variant's styles generated

### ISSUE THREAD

**Issue by thetiby** [chakra-ui/panda#1093]
### Description

Recipe extraction when multiple recipes are used on the same component doesn't work when selecting variants for those recipes.
 
I also included an example to better showcase the issue, alongside with a similar use case that suffers from the same bug.

### Link to Reproduction

https://stackblitz.com/edit/github-cggwkl-43k2mm?file=themePreset.ts,src%2Fapp%2Fpage.tsx,panda.css,panda.config.ts

### Steps to reproduce

1. Go to `themePreset.ts` and notice **the order** of 2 recipes that apply **to the same** 2 JSX elements (for the 2 use cases)
2. Go to `src/app/page.tsx` for the usage
3. Go to `panda.css` and notice the relevant styles (run `panda cssgen --outfile panda.css` to get a fresh file)

```css
@layer recipes {
  .recipe1--borderStyle_orange {
    border: 10px solid orange
    }

  .recipe1--borderStyle_coral {
    border: 10px solid coral
    }

  .recipe2--bgStyle_lightgreen {
    background: lightgreen
    }

  @layer _base {
    .recipe1 {
      padding: 30px
        }

    .recipe1,.recipe2 {
      display: flex
        }
    }
}
``` 
4. The next app suffers from the same issue (using the PostCSS plugin), as it can be noticed:
![image](https://github.com/chakra-ui/panda/assets/2418978/8b5b6d85-0182-454d-af34-8658c0e52a63)

### JS Framework

React (TS)

### Panda CSS Version

0.7.0

### Browser

Google Chrome Version 114.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

[There is a fix](https://github.com/chakra-ui/panda/pull/879) that addressed an older issue, where multiple recipes did not work at all on a single JSX element. However, as we can see [in the tests for that fix](https://github.com/chakra-ui/panda/pull/879/files#diff-574b47b98600b2117540eaa3e43de60d9607b477fc93a8fbdcf0b5d73edde332R289), only the base CSS styles (the `color` property) were addressed, missing `fontSize` property of the `variant=small` 

Thank you for taking the time and for your quick turnaround!
