### ISSUE TITLE
Wrong config.hash documentation

### ISSUE THREAD

**Issue by moxival** [chakra-ui/panda#1296]
### Subject

Config hash

### Description

The documentation for config.hash is wrong (https://panda-css.com/docs/references/config#hash). Currently it states that setting hash to true will hash the class names and the given example confirms this

```css
.dOFUTE {
  color: var(--colors-blue-500);
}
```

In reality, if you set the hash to true, the variable names will be hashed as well and the result will be something like:

```css
.dOFUTE {
  color: var(--ABCDE);
}
```

I am not sure if the documentation is wrong or the implementation is wrong but one should be fixed :)
