### ISSUE TITLE
Config recipe doesn't generate css that is being used

### ISSUE THREAD

**Issue by rendaardy** [chakra-ui/panda#1443]
### Description

When I'm using config recipe to define button recipe, some variants don't generate css even if it's being used.

Example
```js
import { center } from 'styled-system/patterns';
import { button } from 'styled-system/recipes'

export const App = () => {
  return (
    <div
      className={center({
        h: 'full',
      })}
    >
      <button className={button()}>button 1</button>
      <button className={button({ visual: "edgy" })}>button 2</button>
    </div>
  );
};
```

Generated css output
```css
@layer recipes {
  .button--visual_funky {
    background: var(--colors-red-200);
    color: var(--colors-white);
  }

  .button--size_sm {
    padding: var(--spacing-4);
    font-size: 12px;
  }

  .button--shape_circle {
    border-radius: var(--radii-full);
  }

  @layer _base {
    .button {
      display: flex;
    }
  }
}
```

Panda config file
```js
import { defineConfig, defineRecipe } from '@pandacss/dev';

const buttonRecipe = defineRecipe({
  className: 'button',
  description: 'The styles for the Button component',
  base: {
    display: 'flex'
  },
  variants: {
    visual: {
      funky: { bg: 'red.200', color: 'white' },
      edgy: { border: '1px solid {colors.red.500}' }
    },
    size: {
      sm: { padding: '4', fontSize: '12px' },
      lg: { padding: '8', fontSize: '40px' }
    },
    shape: {
      square: { borderRadius: '0' },
      circle: { borderRadius: 'full' }
    }
  },
  defaultVariants: {
    visual: 'funky',
    size: 'sm',
    shape: 'circle'
  }
})

export const config = defineConfig({
  theme: { 
    extend: {
      recipes: {
        button: buttonRecipe,
      },
    },
  },
  globalCss: {
    html: {
      h: 'full',
    },
    body: {
      bg: { base: 'white', _dark: '#2C2C2C' },
    },
  },
  jsxFramework: 'react',
});
```

### Link to Reproduction

https://play.panda-css.com/ruenrkZHFa

### Steps to reproduce

1. Go to the link above and look at generated css for `@layer recipes`

### JS Framework

React

### Panda CSS Version

0.15.3

### Browser

Firefox 117.0.1

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux
