### ISSUE TITLE
staticCss settings configured in recipe/slotRecipe not generating expected static CSS

### ISSUE THREAD

**Issue by amandaguthrie** [chakra-ui/panda#1897]
### Description

When I added `staticCss` to a `recipe` config, I expected the variant styles to be generated like they are when the recipe variants are included in `staticCss.recipes` in the `panda.config.ts` file. (ref: [Panda Docs - Generating Recipes](https://panda-css.com/docs/guides/static#generating-recipes) - second example). 

What I am seeing is that only the default variants and in-use variants are generated.

Workaround is to set the `staticCss` for recipes and slot recipes in the `panda.config.ts` file, which is working as expected.

### Link to Reproduction

[CodeSandbox link](https://codesandbox.io/p/devbox/panda-css-0-23-staticcss-in-recipe-config-repro-yjfl3y?file=%2Fpanda.config.ts&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqv5ei590007356lwegild9x%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqv5ei580002356lnls845c5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqv5ei580004356l5r2usng2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqv5ei580006356l7lgmlmtg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqv5ei580002356lnls845c5%2522%253A%257B%2522id%2522%253A%2522clqv5ei580002356lnls845c5%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqv5ei580001356lsf5odb5a%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqva1e8x0002356lcps1gozn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A21%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A21%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fpanda.config.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqva1e8x0002356lcps1gozn%2522%257D%252C%2522clqv5ei580006356l7lgmlmtg%2522%253A%257B%2522id%2522%253A%2522clqv5ei580006356l7lgmlmtg%2522%252C%2522activeTabId%2522%253A%2522clqv78kr9020m356lo5nvtrcd%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqv5ei580005356l7tdg2pos%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522clqv78kr9020m356lo5nvtrcd%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clqv5ei580004356l5r2usng2%2522%253A%257B%2522id%2522%253A%2522clqv5ei580004356l5r2usng2%2522%252C%2522activeTabId%2522%253A%2522clqv5nto200j3356lh3q7iyb6%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqv5ei580003356ltv91yurn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clqv5nto200j3356lh3q7iyb6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clqv5ntbq003wedfbemi22pmh%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. Fork sandbox in reproduction link
1. Go `src/lib/components/icon/Icon.recipe.ts` and note `staticCss` setting. is set to. I also tried with  `["*"]`, `[{size: ["*"]}]` and listing out the individual sizes. Can also check `src/lib/components/button/Button.recipe.ts` for a slot recipe example.
1. In the terminal run `npx panda cssgen`
1. Go to `styled-system/styles.css`. Search for `.icon` and note that the base style and default size (`md`) are generated, but not the other sizes.  Icon recipe output for comparison with later example. Search for `.button` and note .button__root-size-_md and a few other variants are missing.
```css
@layer recipes{
  .icon--size_md{
    --icon-size: var(--font-sizes-md);
  }

  @layer _base{
    .icon{
      --icon-size: var(--font-sizes-xs);
      height: var(--icon-size);
      width: var(--icon-size);
    }
  }
}
```
5. Go to `panda.config.ts` and uncomment out the `staticCss` block and save.
```ts
  staticCss: {
     recipes: {
       button: ["*"],
       icon: ["*"]
     }
   },
```
6. In the terminal run `npx panda cssgen`
7. Go to `styled-system/styles.css` and note that the base style and all sizes are generated for both button and icon. Icon recipe output below for comparison.
```css
@layer recipes{
  .icon--size_xs{
    --icon-size: var(--font-sizes-xs);
  }

  .icon--size_sm{
    --icon-size: var(--font-sizes-sm);
    color: grass.12;
  }

  .icon--size_lg{
    --icon-size: var(--font-sizes-lg);
  }

  .icon--size_xl{
    --icon-size: var(--font-sizes-xl);
    height: var(--icon-size);
    width: var(--icon-size);
  }

  .icon--size_md{
    --icon-size: var(--font-sizes-md);
  }
  
    @layer _base{
    .icon{
      --icon-size: var(--font-sizes-xs);
      height: var(--icon-size);
      width: var(--icon-size);
    }
  }
```

### JS Framework

Svelte (TS)

### Panda CSS Version

0.23.0

### Browser

Google Chrome 120.0.6099.130, Firefox 121.0

### Operating System

- [ ] macOS
- [X] Windows
- [X] Linux

### Additional Information

Thanks for all of your hard work on Panda CSS! I am enjoying working with it.
