### ISSUE TITLE
Responsive rule insertion order in HMR updates

### ISSUE THREAD

**Issue by chrislopresto** [chakra-ui/panda#2033]
### Description

Thanks for the excellent work on Panda so far!

I encountered what appears to be a bug with rule insertion order in HMR updates. While changing responsive styles, the cssText written during HMR update appears to have order issues that break the responsive behavior.

I included a repro and details below. I'm happy to help troubleshoot further. Please let me know how I can help. Thanks again!

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-wkmtpu?file=src%2FApp.tsx,panda.config.ts&terminal=dev

### Steps to reproduce

Since the issue deals with HMR insertion order affecting responsive styles, the steps to repro involve some setup.

I created this [Stackblitz repro](https://stackblitz.com/edit/vitejs-vite-wkmtpu?file=src%2FApp.tsx,panda.config.ts&terminal=dev) and recorded a screen capture of the steps detailed below.

![panda-hmr-responsive-bug](https://github.com/chakra-ui/panda/assets/93691/713f65e2-b56d-4947-8af6-9830a8e16911)

Steps to repro:
1. Create a ruleset with a base rule and a responsive rule that overrides it, e.g. a color that that goes from "blue" to "orange":
    ```ts
    css({
      color: {
        base: 'blue',
        sm: 'orange',
      });
    ```
1. Resize the window to observe the appropriate responsive styles
1. Change the base rule, e.g. change "blue" to "red"
    ```ts
    css({
      color: {
        base: 'red',
        sm: 'orange',
      });
    ```
1. After the HMR update, resize the window to observe the new base style incorrectly overriding the preexisting responsive style.

### Panda CSS Version

0.27.3

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

- Underlying cause in the [Stackblitz repro](https://stackblitz.com/edit/vitejs-vite-wkmtpu?file=src%2FApp.tsx,panda.config.ts&terminal=dev) is that the red color rule gets is inserted after the preexisting min-width sm media query-wrapped orange color rule. Here's the generated CSS:
    ```css
    @layer utilities {
      .text_blue {
        color: var(--colors-blue);
      }
    
      @media screen and (min-width: 27.5em) {
        .sm\:text_orange {
          color: var(--colors-orange);
        }
      }
    
      .text_red {
        color: var(--colors-red);
      }
    }
    ```
- The error emerged somewhere between panda 0.18.0 and 0.27.3.
- Had the color red rule already existed, we wouldn't encounter the bug. So the bug appears to be isolated to HMR insertion order. Here's the generated CSS on initial load when a different element specifies color red:
    ```css
    @layer utilities {
      .text_blue {
        color: var(--colors-blue);
      }

      .text_red {
        color: var(--colors-red);
      }

      @media screen and (min-width: 27.5em) {
        .sm\:text_orange {
          color: var(--colors-orange);
        }
      }
    }
    ```
