### ISSUE TITLE
Custom Utility with Shorthand not extracted

### ISSUE THREAD

**Issue by FourwingsY** [chakra-ui/panda#2064]
### Description

When I extend utilities
```js
utilities: {
  extend: {
    coloredBorder: {
      shorthand: 'cb',
      values: ['red', 'green', 'blue'],
      transform(value) {
        return {
          border: `1px solid ${value}`,
        };
      },
    },
  },
},
```

And applied
```jsx
<div className={css({ cb: 'red' })} />
```

Then Only full className is extracted in output style, and shorthand styles are not applied.
```html
// OUTPUT
<div class="cb_red" />

// EXPECTED
<div class="cb_red" />
```

```css
/* OUTPUT */
.custom-border_red {
    border: 1px solid red;
}

/* EXPECTED */
.cb_red {
    border: 1px solid red;
}
```

### Link to Reproduction

https://play.panda-css.com/P9EczbeMuz

### JS Framework

React (TS)

### Panda CSS Version

panda/0.27.3 darwin-arm64 node-v20.9.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux
