### ISSUE TITLE
named containers not generated properly

### ISSUE THREAD

**Issue by VinSpee** [chakra-ui/panda#2119]
### Description

When I used a named container `cq({ name: 'foo' })`, I expected to be able to set a style based on it like this

```tsx
css({
	bg: {
		base: 'cyan',
		'@foo/sm': 'yellow'
	}
});
```

But I cant.

```css
.cq-type_inline-size {
	container-type: inline-size;
}

.cq-name_foo {
	container-name: foo;
}

.bg_cyan {
	background: cyan;
}

@foo/sm {
	.\[\@foo\/sm\]\:bg_yellow {
		background: yellow;
	}
}
```

Yet, unnamed containers seem to work fine.

### Link to Reproduction

https://play.panda-css.com/Y1i_FSGeRj

### Steps to reproduce

1. create a named container `cq({ name: 'foo' })`
2. use it
3. see that the proper CSS is not generated

### Panda CSS Version

0.29.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
