### ISSUE TITLE
Responsive staticCss not generated when completely overriding presets

### ISSUE THREAD

**Issue by adbutterfield** [chakra-ui/panda#2174]
### Description

Not sure if this is expected behavior or not.

With this config:
```
  staticCss: {
    css: [
      {
        properties: {
          margin: ["*"],
        },
        responsive: true,
      },
    ],
  },
```

I get this css:
```css
@layer utilities{

  .m_auto {
    margin: auto;
}

  @media screen and (min-width: 40em) {
    .sm\:m_auto {
      margin: auto;
}
}

  @media screen and (min-width: 48em) {
    .md\:m_auto {
      margin: auto;
}
}

  @media screen and (min-width: 64em) {
    .lg\:m_auto {
      margin: auto;
}
}

  @media screen and (min-width: 80em) {
    .xl\:m_auto {
      margin: auto;
}
}

  @media screen and (min-width: 96em) {
    .\32xl\:m_auto {
      margin: auto;
}
}
}
```

With this config:
```
  presets: [],
  staticCss: {
    css: [
      {
        properties: {
          margin: ["*"],
        },
        responsive: true,
      },
    ],
  },
```

I get this css:
```css
@layer utilities{

  .m_auto {
    margin: auto;
}
}
```

### Link to Reproduction

https://play.panda-css.com/8ATd83Lt2U

### Steps to reproduce

Run `panda` on a project with a config file containing the following:
```
  presets: [],
  staticCss: {
    css: [
      {
        properties: {
          margin: ["*"],
        },
        responsive: true,
      },
    ],
  },
```

### Panda CSS Version

0.30.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
