### ISSUE TITLE
`backdropFilter` token generated by lightningcss is invalid

### ISSUE THREAD

**Issue by schardev** [chakra-ui/panda#2539]
### Description

Setting `backdropFilter: 'auto'` **without** `lightingcss` emits proper css with prefixed and non-prefixed token:

```css
  .backdrop_auto {
    backdrop-filter: var(--backdrop-blur,) var(--backdrop-brightness,)
      var(--backdrop-contrast,) var(--backdrop-grayscale,)
      var(--backdrop-hue-rotate,) var(--backdrop-invert,)
      var(--backdrop-opacity,) var(--backdrop-saturate,) var(--backdrop-sepia,);
    -webkit-backdrop-filter: var(--backdrop-blur,) var(--backdrop-brightness,)
      var(--backdrop-contrast,) var(--backdrop-grayscale,)
      var(--backdrop-hue-rotate,) var(--backdrop-invert,)
      var(--backdrop-opacity,) var(--backdrop-saturate,) var(--backdrop-sepia,);
  }
```

After setting `lightningcss`  to `true` it only emits `-webkit` prefix-ed declaration:

```css
@layer utilities {
  .backdrop_sm {
    -webkit-backdrop-filter: var(--backdrop-blur,) var(--backdrop-brightness,)
      var(--backdrop-contrast,) var(--backdrop-grayscale,)
      var(--backdrop-hue-rotate,) var(--backdrop-invert,)
      var(--backdrop-opacity,) var(--backdrop-saturate,) var(--backdrop-sepia,);  }
}

```

[see also: #2329]

### Link to Reproduction

https://play.panda-css.com/Gm2JYulBWj

### JS Framework

React

### Panda CSS Version

0.37.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
