### ISSUE TITLE
Allow to define`@font-face` in `panda.config.ts`

### ISSUE THREAD

**Issue by azu** [chakra-ui/panda#2729]
### Description

I want to define multiple `@font-face` in `panda.config.ts` for alias with custom font weight.
Currently, Hiragino Font has a Weight problem in Japanese, so I define the following normalized font with adjusted weight in `global.css` and use it.

Example my `global.css`

```css
@layer reset, base, tokens, recipes, utilities;

/*
 * Fix iOS font weight issue
 * It is workaround for apple font weight issue
 * Ref: 
 * https://github.com/flutter/flutter/issues/132475
 * - https://pocket-base.com/blog/2023/09/iphone-ipad-hiragino/
 */
@font-face {
    font-family: "Fixme-Hiragino-Sans";
    src: local("HiraginoSans-W1"), local("HiraginoSans-W3");
    font-weight: 100;
}

@font-face {
    font-family: "Fixme-Hiragino-Sans";
    src: local("HiraginoSans-W2"), local("HiraginoSans-W3");
    font-weight: 200;
}

@font-face {
    font-family: "Fixme-Hiragino-Sans";
    src: local("HiraginoSans-W3");
    font-weight: 300;
}

@font-face {
    font-family: "Fixme-Hiragino-Sans";
    src: local("HiraginoSans-W4"), local("HiraginoSans-W3");
    font-weight: 400;
}

@font-face {
    font-family: "Fixme-Hiragino-Sans";
    src: local("HiraginoSans-W5"), local("HiraginoSans-W6");
    font-weight: 500;
}

@font-face {
    font-family: "Fixme-Hiragino-Sans";
    src: local("HiraginoSans-W6");
    font-weight: 600;
}

@font-face {
    font-family: "Fixme-Hiragino-Sans";
    src: local("HiraginoSans-W6");
    font-weight: 700;
}

@font-face {
    font-family: "Fixme-Hiragino-Sans";
    src: local("HiraginoSans-W8"), local("HiraginoSans-W7");
    font-weight: 800;
}

@font-face {
    font-family: "Fixme-Hiragino-Sans";
    src: local("HiraginoSans-W9"), local("HiraginoSans-W8"),
    local("HiraginoSans-W7");
    font-weight: 900;
}
```

and refer it from panda.config.ts

```ts
import { defineConfig, defineGlobalStyles } from "@pandacss/dev";
const globalCss = defineGlobalStyles({
  // Can not define @font-face in globalCSS. These font-face is defined in global.css...
  "html,body": {
    fontFamily: "base",
  },
})
export default defineConfig({
  globalCss,
  presets: ['@pandacss/preset-base'],
  preflight: true,
  include: ["./src/components/**/*.{ts,tsx,js,jsx}", "./src/app/**/*.{ts,tsx,js,jsx}"],
  exclude: [],
  shorthands: false,
  strictTokens: true,
  strictPropertyValues: true,
  polyfill: true,
  // Useful for theme customization
  theme: {
    tokens: {
      // TODO: It depended on global.css. It is not sharable.
      // Want to define Fixme-Hiragino-Sans into panda.config.ts
      fonts: {
        "base": {
          value: "Fixme-Hiragino-Sans, Meiryo, sans-serif",
        },
      },
      // variaous tokens…
  },
  outdir: "styled-system"
});

```

However, defining `@font-face` in `global.css` is not ideal.
Because I would like to share this `fonts` token setting among multiple web applications in monorepo, but I feel that global.css is difficult to share.

If possible, I would like to define `@font-face` in panda.config.ts.

### Problem Statement/Justification

I want to my design token between applications.
I would like to share everything including font-face with panda preset etc.

- [Presets - Panda CSS](https://panda-css.com/docs/customization/presets)

However, `global.css` requires copy and paste…

### Proposed Solution or API

I would like to have an API that allows me to define font-face in panda.config.ts like the following

- `defineFontFace`
- `defineGlobalCss(`/* css string */)`

### Alternatives

- Sharable `global.css`

### Additional Information

- Example repository: [azu/pandacss-font-face-global-css: panda css disallow to define @font-face on `globalCss`](https://github.com/azu/pandacss-font-face-global-css)
  - This repo use `global.css` for workaround
- Similar Question on Stackoverflow: [roboto - How to write the multiple font faces inside defineGlobalStyles in Panda css - Stack Overflow](https://stackoverflow.com/questions/78587384/how-to-write-the-multiple-font-faces-inside-defineglobalstyles-in-panda-css)
