### ISSUE TITLE
'divide' utility doesn't work as expected when used in recipes

### ISSUE THREAD

**Issue by esou** [chakra-ui/panda#2772]
### Description

When I use divideY & divideColor in config recipes, I expect the generated code to look like this : 

```css
  .divided-recipe > :not([hidden]) ~ :not([hidden]) {
      border-color: red;
      border-top-width: 1px;
      border-bottom-width: 0px;
  }
```
but it looks like this 

```css
  .divided-recipe > :not([hidden]) ~ :not([hidden]) {
      border-color: red;
  }
```

### Link to Reproduction

https://play.panda-css.com/AilBWfxQu5

### Steps to reproduce

see playground link, you can comment the color in recipe definition to see the divider appear

### Panda CSS Version

tested in 0.39.0 & 0.44.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux
