### ISSUE TITLE
defineGlobalCss is ignoring <p> element

### ISSUE THREAD

**Issue by dannylin108** [chakra-ui/panda#2856]
### Description

I have a global css definition:

```TS
import { defineGlobalStyles } from '@pandacss/dev'

const globalCss = defineGlobalStyles({
    '.book-content': {
        p: {
            marginBottom: '1rem',
            lineHeight: '1.6',
            fontSize: '1rem',
        },
        'li': {
            marginBottom: '0.5rem',
        },
    }
});

export default globalCss;
```

but neither in the app, nor with `panda cssgen` can't get styles for `p`, it's just ignored

```CSS

 .book-content {
    margin-bottom: 1rem;
    line-height: 1.6;
    font-size: 1rem;
}

  .book-content li {
    margin-bottom: 0.5rem;
}
```

### Link to Reproduction

https://stackblitz.com/~/github.com/dannylin108/panda-bug-report

### Steps to reproduce

1. Wait till stackblitz initialize the app
2. Check styles of paragraphs inside grey box with DevTools
3. run `panda cssgen`
4. check styles inside `styled-system/styles.css`

### JS Framework

Solid TS

### Panda CSS Version

0.45.2

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
