### ISSUE TITLE
Hi. I fount the unexpected behavior when using `grid-column`

### ISSUE THREAD

**Issue by nayounsang** [chakra-ui/panda#2917]
### Description

```css
.grid-c_2 {
    grid-column: span 2 / span 2;
}
```
When I use `gridColumn: number` in `{ css } from "@/styled-system/css";`,
It is converted to unexpected css.  

### Link to Reproduction

https://play.panda-css.com/dq7CyJZHZD

### Steps to reproduce

1. `import { css } from "@/styled-system/css";`
2. `<div className={css({ gridColumn: 2 })}>{children}</div>` or ` <div className={css({ gridColumn: "2" })}>{children}</div>`
3. Converted to
```css
.grid-c_2 {
    grid-column: span 2 / span 2;
}
```
4. It is not
```css
.grid-c_2 {
    grid-column: 2;
}
```
I see the unexpected layout.

### JS Framework

React, Nextjs

### Panda CSS Version

0.42.0

### Browser

Chrome 93

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Is this indented feature?
I can't find this topic when search for `grid` or `column` in docs.
I'm in a situation where it's good to use explicit numbers to meet the designer's requirements.
