### ISSUE TITLE
Invalid selectors are grouped with valid ones when using textStyle

### ISSUE THREAD

**Issue by islami00** [chakra-ui/panda#3095]
### Description

When I apply a textStyle token using an invalid selector, for example:
```jsx
    <div className={css({ textStyle: "t1", "&.&": { textStyle: "t1" }, })}>Test1</div>
```
I expect it not to affect any other styles defined in my project. But, I noticed all places the textStyle was used also lose their styling.

This is because the styles applied by the invalid selector are combined with the styles of the textStyle token itself in the same selector, which causes neither style to be applied as the browser ignores the entire selector.

### Link to Reproduction

https://play.panda-css.com/TWMXkjFGTG

### Steps to reproduce

1. Inspect the text "Test1"
2. Notice how no text style is applied to it
3. Inspect the generated styles in the head tag
4. Notice the invalid combination of the styles

```css
 @layer compositions {

    .textStyle_t1,.\[\&\.\&\]\:textStyle_t1..\[\&\.\&\]\:textStyle_t1 {
      font-size: 12px;
      font-weight: 400;
      line-height: 1.5;
}
```

### JS Framework

React (TS)

### Panda CSS Version

v0.51.1

### Browser

Google Chrome 131.0.6778.265

### Operating System

- [x] macOS
- [ ] Windows
- [ ] Linux
