### ISSUE TITLE
Theme Conditions Not Working with Manual CSS Syntax

### ISSUE THREAD

**Issue by kris-ellery** [chakra-ui/panda#3230]
### Description

Hello! My team is in the process of adding multi-theme support and want to leverage the `themes` feature in config.

When using Panda CSS with multi-theme support, the automatically generated theme conditions (`_theme{Name}`) don't work when used manually in CSS styles.

The following syntax doesn't produce the expected CSS output:

```ts
const colorStyles = css.raw({
  // Does not work
  _themePrimary: {
    color: 'blue'
  },
  _themeSecondary: {
    color: 'red'
  },
  
  // Does not work
  color: {
    _themePrimary: "blue",
    _themeSecondary: 'red'
  },
});
```

Current CSS output

```css
.themePrimary\:c_blue [data-panda-theme="primary"] {
  color: blue;
}

.themeSecondary\:c_red [data-panda-theme="secondary"] {
  color: red;
}
```

Expected CSS output

```css
[data-panda-theme="primary"] .themePrimary\:c_blue {
  color: blue;
}
[data-panda-theme="secondary"] .themeSecondary\:c_red {
  color: red;
}
```

I understand that tokens or semantic tokens could be an alternative solution, but I would prefer to have the ability to use the theme condition syntax shown above to cover edge cases in our theming system.

### Link to Reproduction

https://play.panda-css.com/Noq97KQFke

### Steps to reproduce

1. Go to 'panda.config.ts'
2. Add `themes` with `primary` and `secondary` objects
3. Panda will auto-generate `_themePrimary` and `_themeSecondary` conditions
4. Use either of the conditions
5. Generated CSS is out of order and `data-panda-theme` is after class name, rather than before

### JS Framework

React (TS)

### Panda CSS Version

0.53.3

### Operating System

- [x] macOS
- [ ] Windows
- [ ] Linux
