### ISSUE TITLE
Logical border widths are not getting `borderWidth` tokens

### ISSUE THREAD

**Issue by jimmymorris** [chakra-ui/panda#3237]
### Description

When I use logical borders and want to set their width, I would expect that the borderWidths tokens would be available to use.

```css
.border-block-start-width_test-medium {
  border-block-start-width: test-medium;
}
```

Expected
```css
.border-block-start-width_\{borderWidths\.test-medium\} {
  border-block-start-width: var(--border-widths-test-medium);
}
```

I am only able to use border widths on logical border widths if I use a reference `{borderWidths.*}`

### Link to Reproduction

https://play.panda-css.com/TT-y10HSyl

### Steps to reproduce

1. Go to the Config tab and see the custom test borderWidth tokens.
2. Go to the Code tab and see that `borderBlockStartWidth: 'test-medium'` which does not throw a type error either.
Go to the CSS tab and see the class generated for the `borderBlockStartWidth` is

```css
.border-block-start-width_test-medium {
	border-block-start-width: test-medium;
}
```

Expected
```css
.border-block-start-width_\{borderWidths\.test-medium\} {
	border-block-start-width: var(--border-widths-test-medium);
}
```

### Panda CSS Version

0.53.4

### Operating System

- [x] macOS
- [x] Windows
- [x] Linux

### Additional Information

Other logical border properties like `borderBlockStartColor` does seem to work as expected.
