### ISSUE TITLE
Shouldn't what is referred to as a "semantic token" be better called an "alias token"?

### ISSUE THREAD

**Issue by yuheiy** [chakra-ui/panda#785]
### Description

The term "semantic token" used in Panda CSS may not be quite accurate. This is because what is called a semantic token in Panda CSS seems to be simply an alias token.

### Problem Statement/Justification

Generally speaking, semantic tokens are not necessarily aliases. Moreover, there might be cases where one would want to create non-semantic aliases. For example:

```css
:root {
  --text-primary: #000000;
  --gray: #8E8E93;
  --legacy-gray: var(--gray-900);
}
```

### Proposed Solution or API

Perhaps it would be more appropriate to rename `semanticTokens` to `aliasTokens`. For reference, the term "alias" is borrowed from [Adobe Spectrum](https://spectrum.adobe.com/page/design-tokens/#Design-token-types-and-terminology).
