### ISSUE TITLE
Zero tokens, base and reset variables

### ISSUE THREAD

**Issue by clovis-rosa** [chakra-ui/panda#978]
### Description

I'm playing with Panda using the `"syntax": "template-literal"` styled-components like syntax and I would like to config my own CSS variables/Design System and not use anything that comes with the reset, base or tokens. 

Omit any of these keywords in the `@layer `config in the CSS doesn't work. Delete or edit anything inside the `styled-system` folder doesn't see to be ideal option. So is there a way to get a completely zero CSS? 

### Problem Statement/Justification

Today, out of the box after running build in a Next.js project Panda comes with 650 lines of CSS variables and keyframes that may be no be necessary or entered used, of course respecting everybody's choice on how to deal with styles in their applications.

### Proposed Solution or API

Is it possible to omit those CSS in the config file, like: 

```typescript
{
"layerResetCss": "false", 
"layerBaseCss": "false", 
"layerTokensCss": "false" 
}

// where `true` is the default
```

### Additional Information

Thank you for the amazing work!

**Comment by anubra266** [comment]
@clovis-rosa there's an `eject` option in the config.

**Comment by clovis-rosa** [comment]
@anubra266, first of all, thank you for the fast response!

It worked partially, I still getting some CSS variables from the `@layer base`

```css
*, ::before, ::after, ::backdrop {
	--blur: ;
	--brightness: ;
	--contrast: ;
	--grayscale: ;
	--hue-rotate: ;
	--invert: ;
	--saturate: ;
	--sepia: ;
	--drop-shadow: ;
	--backdrop-blur: ;
	--backdrop-brightness: ;
	--backdrop-contrast: ;
	--backdrop-grayscale: ;
	--backdrop-hue-rotate: ;
	--backdrop-invert: ;
	--backdrop-opacity: ;
	--backdrop-saturate: ;
	--backdrop-sepia: ;
	--scroll-snap-strictness: proximity;
	--border-spacing-x: 0;
	--border-spacing-y: 0;
	--translate-x: 0;
	--translate-y: 0;
	--rotate: 0;
	--skew-x: 0;
	--skew-y: 0;
	--scale-x: 1;
	--scale-y: 1;
}
```
