### ISSUE TITLE
[NUXT] Panda do not extract the second call to `css` method in vue component.

### ISSUE THREAD

**Issue by Baben01** [chakra-ui/panda#998]
### Description

Hello,
Panda is extracting css only for the first call of `css` function but not the other one present under the `template` part of the component.

### Link to Reproduction

https://stackblitz.com/edit/nuxt-starter-jbiezf?file=styled-system%2Fstyles.css

### Steps to reproduce

On the reproduction link run `npx panda --clean`. The output of `styled-system/style.css` for the `Demo.vue` component is

```css
@layer reset, base, tokens, recipes, utilities;

@import './reset.css';

@import './global.css';

@import './tokens/index.css';

@import './tokens/keyframes.css';

@layer utilities {
  .text_green {
    color: green
    }
}
```

But if you swap the 2 `div` in `Demo.vue` component to have this component : 

```vue
<script setup lang="ts">
import { css } from 'styled-system/css';
</script>

<template>
  <div :class="css({ color: 'red', fontWeight: 'bold' })">
    <p>TEST GREEN</p>
    <div :class="css({ color: 'green' })">
      <p>TEST RED</p>
    </div>
  </div>
</template>

```
Rerun `npx panda --clean` and the output css file become : 
```css
@layer reset, base, tokens, recipes, utilities;

@import './reset.css';

@import './global.css';

@import './tokens/index.css';

@import './tokens/keyframes.css';

@layer utilities {
  .text_red {
    color: red
    }

  .font_bold {
    font-weight: var(--font-weights-bold)
    }
}
```

Still the second call to `css` is not extracted

### JS Framework

Nuxt / TS

### Panda CSS Version

latest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux
